import { defineStore } from 'pinia';

export const useProductStore = defineStore('product', {
  state: () => ({
    products: [
      {
        id: 1,
        name: 'Product 1',
        price: 100,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 1,
      },
      {
        id: 2,
        name: 'Product 2',
        price: 200,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 1,
      },
      {
        id: 3,
        name: 'Product 3',
        price: 300,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 1,
      },
      {
        id: 4,
        name: 'Product 4',
        price: 400,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 1,
      },
      {
        id: 5,
        name: 'Product 5',
        price: 500,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 1,
      },
      {
        id: 6,
        name: 'Product 6',
        price: 600,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 1,
      },
      {
        id: 7,
        name: 'Product 7',
        price: 700,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 1,
      },
      {
        id: 8,
        name: 'Product 8',
        price: 800,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 1,
      },
      {
        id: 9,
        name: 'Product 9',
        price: 900,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 1,
      },
      {
        id: 10,
        name: 'Product 10',
        price: 1000,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 1,
      },
      {
        id: 11,
        name: 'Product 11',
        price: 1100,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 2,
      },
      {
        id: 12,
        name: 'Product 12',
        price: 1200,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 2,
      },
      {
        id: 13,
        name: 'Product 13',
        price: 1300,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 2,
      },
      {
        id: 14,
        name: 'Product 14',
        price: 1400,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 2,
      },
      {
        id: 15,
        name: 'Product 15',
        price: 1500,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 2,
      },
      {
        id: 16,
        name: 'Product 16',
        price: 1600,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 2,
      },
      {
        id: 17,
        name: 'Product 17',
        price: 1700,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 2,
      },
      {
        id: 18,
        name: 'Product 18',
        price: 1800,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 2,
      },
      {
        id: 19,
        name: 'Product 19',
        price: 1900,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 2,
      },
      {
        id: 20,
        name: 'Product 20',
        price: 2000,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 2,
      },
      {
        id: 21,
        name: 'Product 21',
        price: 2100,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 3,
      },
      {
        id: 22,
        name: 'Product 22',
        price: 2200,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 3,
      },
      {
        id: 23,
        name: 'Product 23',
        price: 2300,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 3,
      },
      {
        id: 24,
        name: 'Product 24',
        price: 2400,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 3,
      },
      {
        id: 25,
        name: 'Product 25',
        price: 2500,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 3,
      },
      {
        id: 26,
        name: 'Product 26',
        price: 2600,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 3,
      },
      {
        id: 27,
        name: 'Product 27',
        price: 2700,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 3,
      },
      {
        id: 28,
        name: 'Product 28',
        price: 2800,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 3,
      },
      {
        id: 29,
        name: 'Product 29',
        price: 2900,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 3,
      },
      {
        id: 30,
        name: 'Product 30',
        price: 3000,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 3,
      },
      {
        id: 31,
        name: 'Product 31',
        price: 3100,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 4,
      },
      {
        id: 32,
        name: 'Product 32',
        price: 3200,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 4,
      },
      {
        id: 33,
        name: 'Product 33',
        price: 3300,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 4,
      },
      {
        id: 34,
        name: 'Product 34',
        price: 3400,
        image: 'https://cdn.quasar.dev/img/avatar.png',
        isActive: true,
        category: 4,
      },
    ],
  }),
  getters: {
    getProducts: (state) => state.products,
    getProductById: (state) => (id: any) =>
      state.products.find((product) => product.id === id),
    getProductsByCategory: (state) => (category: any) =>
      state.products.filter((product) => product.category === category),
  },
  actions: {
    addNewProduct(product: any) {
      product.id = this.products.length + 1;
      this.products.push(product);
      return this.products;
    },
    updateProduct(product: any) {
      const index = this.products.findIndex((p) => p.id === product.id);
      Object.assign(this.products[index], product);
      return this.products;
    },
    deleteProduct(id: any) {
      const index = this.products.findIndex((p) => p.id === id);
      this.products.splice(index, 1);
      return this.products;
    },
    assignCategoryToProduct(product: any, category: any) {
      product.category = category;
      return this.products;
    },
  },
});
